# Generated by Django 4.2.5 on 2023-09-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_delivery_fee_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_fee',
        ),
    ]
